name: blog_app
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  supabase_flutter: 
  flutter_bloc:
  get_it:
  dotted_border: ^2.1.0
  image_picker: ^1.1.0
  
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.3.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
